// ServerService — read/control RPCs served by the server and consumed by UI clients
// (and any human tooling such as grpcurl).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/server.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/workflow-example/criteria-k8s/internal/criteria/pb/criteria/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerServiceName is the fully-qualified name of the ServerService service.
	ServerServiceName = "criteria.v1.ServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerServiceListAgentsProcedure is the fully-qualified name of the ServerService's ListAgents
	// RPC.
	ServerServiceListAgentsProcedure = "/criteria.v1.ServerService/ListAgents"
	// ServerServiceGetAgentProcedure is the fully-qualified name of the ServerService's GetAgent RPC.
	ServerServiceGetAgentProcedure = "/criteria.v1.ServerService/GetAgent"
	// ServerServiceListRunsProcedure is the fully-qualified name of the ServerService's ListRuns RPC.
	ServerServiceListRunsProcedure = "/criteria.v1.ServerService/ListRuns"
	// ServerServiceGetRunProcedure is the fully-qualified name of the ServerService's GetRun RPC.
	ServerServiceGetRunProcedure = "/criteria.v1.ServerService/GetRun"
	// ServerServiceListRunEventsProcedure is the fully-qualified name of the ServerService's
	// ListRunEvents RPC.
	ServerServiceListRunEventsProcedure = "/criteria.v1.ServerService/ListRunEvents"
	// ServerServiceWatchRunProcedure is the fully-qualified name of the ServerService's WatchRun RPC.
	ServerServiceWatchRunProcedure = "/criteria.v1.ServerService/WatchRun"
	// ServerServiceStopRunProcedure is the fully-qualified name of the ServerService's StopRun RPC.
	ServerServiceStopRunProcedure = "/criteria.v1.ServerService/StopRun"
	// ServerServicePauseRunProcedure is the fully-qualified name of the ServerService's PauseRun RPC.
	ServerServicePauseRunProcedure = "/criteria.v1.ServerService/PauseRun"
	// ServerServiceResumeRunProcedure is the fully-qualified name of the ServerService's ResumeRun RPC.
	ServerServiceResumeRunProcedure = "/criteria.v1.ServerService/ResumeRun"
	// ServerServiceInspectRunProcedure is the fully-qualified name of the ServerService's InspectRun
	// RPC.
	ServerServiceInspectRunProcedure = "/criteria.v1.ServerService/InspectRun"
	// ServerServiceSubmitWorkflowAssignmentProcedure is the fully-qualified name of the ServerService's
	// SubmitWorkflowAssignment RPC.
	ServerServiceSubmitWorkflowAssignmentProcedure = "/criteria.v1.ServerService/SubmitWorkflowAssignment"
	// ServerServiceGetAssignmentDispositionProcedure is the fully-qualified name of the ServerService's
	// GetAssignmentDisposition RPC.
	ServerServiceGetAssignmentDispositionProcedure = "/criteria.v1.ServerService/GetAssignmentDisposition"
	// ServerServiceSendPromptProcedure is the fully-qualified name of the ServerService's SendPrompt
	// RPC.
	ServerServiceSendPromptProcedure = "/criteria.v1.ServerService/SendPrompt"
)

// ServerServiceClient is a client for the criteria.v1.ServerService service.
type ServerServiceClient interface {
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
	ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error)
	// WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
	// persisted events (since `since_seq`) and then tails live events until the
	// client disconnects or the run reaches a terminal state.
	WatchRun(context.Context, *connect.Request[v1.WatchRunRequest]) (*connect.ServerStreamForClient[v1.Envelope], error)
	// StopRun cancels a run. If an agent is attached to the run via its
	// Control stream, the orchestrator pushes a RunCancel to it. Returns
	// FAILED_PRECONDITION if the agent is not connected.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's agent.
	StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error)
	// PauseRun halts a run without losing state. The adapter session is
	// paused via the v2 adapter Pause RPC.
	PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error)
	// ResumeRun continues a previously paused run.
	ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.ResumeRunResponse], error)
	// InspectRun returns structured read-only state for a run. If session_id
	// is empty the server may return a summary across all sessions.
	InspectRun(context.Context, *connect.Request[v1.InspectRunRequest]) (*connect.Response[v1.InspectRunResponse], error)
	// SubmitWorkflowAssignment enqueues a workflow for execution by a long-lived
	// Criteria agent. The orchestrator creates the run, records the assignment,
	// and returns the run id along with the current assignment state.
	//
	// Authorization: implementations MUST authenticate the caller. The
	// assignment record is owned by the authenticated submitting caller;
	// callers are permitted to inspect or cancel assignments they own.
	// Implementations MAY additionally enforce service-level authorization
	// (namespace, role, or policy checks). The run itself executes on the
	// agent that later leases the assignment, but ownership of the assignment
	// record remains with the submitting caller.
	//
	// Idempotency: if `idempotency_key` is non-empty and a previous submission
	// with the same key already exists in the caller's scope, the server MUST
	// return the existing `run_id` and current state without creating a
	// duplicate run or assignment.
	SubmitWorkflowAssignment(context.Context, *connect.Request[v1.SubmitWorkflowAssignmentRequest]) (*connect.Response[v1.SubmitWorkflowAssignmentResponse], error)
	// GetAssignmentDisposition returns the current queue state of a previously
	// submitted workflow assignment.
	//
	// Authorization: implementations MUST reject the request with
	// PERMISSION_DENIED if the authenticated caller does not own the assignment.
	// Run ownership is distinct from assignment ownership: agents lease and
	// execute runs via the Control stream, but the assignment record remains
	// owned by the submitting caller.
	GetAssignmentDisposition(context.Context, *connect.Request[v1.GetAssignmentDispositionRequest]) (*connect.Response[v1.GetAssignmentDispositionResponse], error)
	// SendPrompt delivers a prompt to the agent executing a specific run step.
	// The prompt is sent over the Criteria Control stream; callers must own the run.
	SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error)
}

// NewServerServiceClient constructs a client for the criteria.v1.ServerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverServiceMethods := v1.File_criteria_v1_server_proto.Services().ByName("ServerService").Methods()
	return &serverServiceClient{
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+ServerServiceListAgentsProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.Agent](
			httpClient,
			baseURL+ServerServiceGetAgentProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v1.ListRunsRequest, v1.ListRunsResponse](
			httpClient,
			baseURL+ServerServiceListRunsProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v1.GetRunRequest, v1.Run](
			httpClient,
			baseURL+ServerServiceGetRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRunEvents: connect.NewClient[v1.ListRunEventsRequest, v1.ListRunEventsResponse](
			httpClient,
			baseURL+ServerServiceListRunEventsProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListRunEvents")),
			connect.WithClientOptions(opts...),
		),
		watchRun: connect.NewClient[v1.WatchRunRequest, v1.Envelope](
			httpClient,
			baseURL+ServerServiceWatchRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("WatchRun")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[v1.StopRunRequest, v1.StopRunResponse](
			httpClient,
			baseURL+ServerServiceStopRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
		pauseRun: connect.NewClient[v1.PauseRunRequest, v1.PauseRunResponse](
			httpClient,
			baseURL+ServerServicePauseRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("PauseRun")),
			connect.WithClientOptions(opts...),
		),
		resumeRun: connect.NewClient[v1.ResumeRunRequest, v1.ResumeRunResponse](
			httpClient,
			baseURL+ServerServiceResumeRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ResumeRun")),
			connect.WithClientOptions(opts...),
		),
		inspectRun: connect.NewClient[v1.InspectRunRequest, v1.InspectRunResponse](
			httpClient,
			baseURL+ServerServiceInspectRunProcedure,
			connect.WithSchema(serverServiceMethods.ByName("InspectRun")),
			connect.WithClientOptions(opts...),
		),
		submitWorkflowAssignment: connect.NewClient[v1.SubmitWorkflowAssignmentRequest, v1.SubmitWorkflowAssignmentResponse](
			httpClient,
			baseURL+ServerServiceSubmitWorkflowAssignmentProcedure,
			connect.WithSchema(serverServiceMethods.ByName("SubmitWorkflowAssignment")),
			connect.WithClientOptions(opts...),
		),
		getAssignmentDisposition: connect.NewClient[v1.GetAssignmentDispositionRequest, v1.GetAssignmentDispositionResponse](
			httpClient,
			baseURL+ServerServiceGetAssignmentDispositionProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetAssignmentDisposition")),
			connect.WithClientOptions(opts...),
		),
		sendPrompt: connect.NewClient[v1.SendPromptRequest, v1.SendPromptResponse](
			httpClient,
			baseURL+ServerServiceSendPromptProcedure,
			connect.WithSchema(serverServiceMethods.ByName("SendPrompt")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverServiceClient implements ServerServiceClient.
type serverServiceClient struct {
	listAgents               *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	getAgent                 *connect.Client[v1.GetAgentRequest, v1.Agent]
	listRuns                 *connect.Client[v1.ListRunsRequest, v1.ListRunsResponse]
	getRun                   *connect.Client[v1.GetRunRequest, v1.Run]
	listRunEvents            *connect.Client[v1.ListRunEventsRequest, v1.ListRunEventsResponse]
	watchRun                 *connect.Client[v1.WatchRunRequest, v1.Envelope]
	stopRun                  *connect.Client[v1.StopRunRequest, v1.StopRunResponse]
	pauseRun                 *connect.Client[v1.PauseRunRequest, v1.PauseRunResponse]
	resumeRun                *connect.Client[v1.ResumeRunRequest, v1.ResumeRunResponse]
	inspectRun               *connect.Client[v1.InspectRunRequest, v1.InspectRunResponse]
	submitWorkflowAssignment *connect.Client[v1.SubmitWorkflowAssignmentRequest, v1.SubmitWorkflowAssignmentResponse]
	getAssignmentDisposition *connect.Client[v1.GetAssignmentDispositionRequest, v1.GetAssignmentDispositionResponse]
	sendPrompt               *connect.Client[v1.SendPromptRequest, v1.SendPromptResponse]
}

// ListAgents calls criteria.v1.ServerService.ListAgents.
func (c *serverServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// GetAgent calls criteria.v1.ServerService.GetAgent.
func (c *serverServiceClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListRuns calls criteria.v1.ServerService.ListRuns.
func (c *serverServiceClient) ListRuns(ctx context.Context, req *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// GetRun calls criteria.v1.ServerService.GetRun.
func (c *serverServiceClient) GetRun(ctx context.Context, req *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRunEvents calls criteria.v1.ServerService.ListRunEvents.
func (c *serverServiceClient) ListRunEvents(ctx context.Context, req *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error) {
	return c.listRunEvents.CallUnary(ctx, req)
}

// WatchRun calls criteria.v1.ServerService.WatchRun.
func (c *serverServiceClient) WatchRun(ctx context.Context, req *connect.Request[v1.WatchRunRequest]) (*connect.ServerStreamForClient[v1.Envelope], error) {
	return c.watchRun.CallServerStream(ctx, req)
}

// StopRun calls criteria.v1.ServerService.StopRun.
func (c *serverServiceClient) StopRun(ctx context.Context, req *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// PauseRun calls criteria.v1.ServerService.PauseRun.
func (c *serverServiceClient) PauseRun(ctx context.Context, req *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error) {
	return c.pauseRun.CallUnary(ctx, req)
}

// ResumeRun calls criteria.v1.ServerService.ResumeRun.
func (c *serverServiceClient) ResumeRun(ctx context.Context, req *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.ResumeRunResponse], error) {
	return c.resumeRun.CallUnary(ctx, req)
}

// InspectRun calls criteria.v1.ServerService.InspectRun.
func (c *serverServiceClient) InspectRun(ctx context.Context, req *connect.Request[v1.InspectRunRequest]) (*connect.Response[v1.InspectRunResponse], error) {
	return c.inspectRun.CallUnary(ctx, req)
}

// SubmitWorkflowAssignment calls criteria.v1.ServerService.SubmitWorkflowAssignment.
func (c *serverServiceClient) SubmitWorkflowAssignment(ctx context.Context, req *connect.Request[v1.SubmitWorkflowAssignmentRequest]) (*connect.Response[v1.SubmitWorkflowAssignmentResponse], error) {
	return c.submitWorkflowAssignment.CallUnary(ctx, req)
}

// GetAssignmentDisposition calls criteria.v1.ServerService.GetAssignmentDisposition.
func (c *serverServiceClient) GetAssignmentDisposition(ctx context.Context, req *connect.Request[v1.GetAssignmentDispositionRequest]) (*connect.Response[v1.GetAssignmentDispositionResponse], error) {
	return c.getAssignmentDisposition.CallUnary(ctx, req)
}

// SendPrompt calls criteria.v1.ServerService.SendPrompt.
func (c *serverServiceClient) SendPrompt(ctx context.Context, req *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error) {
	return c.sendPrompt.CallUnary(ctx, req)
}

// ServerServiceHandler is an implementation of the criteria.v1.ServerService service.
type ServerServiceHandler interface {
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
	ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error)
	// WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
	// persisted events (since `since_seq`) and then tails live events until the
	// client disconnects or the run reaches a terminal state.
	WatchRun(context.Context, *connect.Request[v1.WatchRunRequest], *connect.ServerStream[v1.Envelope]) error
	// StopRun cancels a run. If an agent is attached to the run via its
	// Control stream, the orchestrator pushes a RunCancel to it. Returns
	// FAILED_PRECONDITION if the agent is not connected.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's agent.
	StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error)
	// PauseRun halts a run without losing state. The adapter session is
	// paused via the v2 adapter Pause RPC.
	PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error)
	// ResumeRun continues a previously paused run.
	ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.ResumeRunResponse], error)
	// InspectRun returns structured read-only state for a run. If session_id
	// is empty the server may return a summary across all sessions.
	InspectRun(context.Context, *connect.Request[v1.InspectRunRequest]) (*connect.Response[v1.InspectRunResponse], error)
	// SubmitWorkflowAssignment enqueues a workflow for execution by a long-lived
	// Criteria agent. The orchestrator creates the run, records the assignment,
	// and returns the run id along with the current assignment state.
	//
	// Authorization: implementations MUST authenticate the caller. The
	// assignment record is owned by the authenticated submitting caller;
	// callers are permitted to inspect or cancel assignments they own.
	// Implementations MAY additionally enforce service-level authorization
	// (namespace, role, or policy checks). The run itself executes on the
	// agent that later leases the assignment, but ownership of the assignment
	// record remains with the submitting caller.
	//
	// Idempotency: if `idempotency_key` is non-empty and a previous submission
	// with the same key already exists in the caller's scope, the server MUST
	// return the existing `run_id` and current state without creating a
	// duplicate run or assignment.
	SubmitWorkflowAssignment(context.Context, *connect.Request[v1.SubmitWorkflowAssignmentRequest]) (*connect.Response[v1.SubmitWorkflowAssignmentResponse], error)
	// GetAssignmentDisposition returns the current queue state of a previously
	// submitted workflow assignment.
	//
	// Authorization: implementations MUST reject the request with
	// PERMISSION_DENIED if the authenticated caller does not own the assignment.
	// Run ownership is distinct from assignment ownership: agents lease and
	// execute runs via the Control stream, but the assignment record remains
	// owned by the submitting caller.
	GetAssignmentDisposition(context.Context, *connect.Request[v1.GetAssignmentDispositionRequest]) (*connect.Response[v1.GetAssignmentDispositionResponse], error)
	// SendPrompt delivers a prompt to the agent executing a specific run step.
	// The prompt is sent over the Criteria Control stream; callers must own the run.
	SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error)
}

// NewServerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerServiceHandler(svc ServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverServiceMethods := v1.File_criteria_v1_server_proto.Services().ByName("ServerService").Methods()
	serverServiceListAgentsHandler := connect.NewUnaryHandler(
		ServerServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(serverServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetAgentHandler := connect.NewUnaryHandler(
		ServerServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(serverServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceListRunsHandler := connect.NewUnaryHandler(
		ServerServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(serverServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetRunHandler := connect.NewUnaryHandler(
		ServerServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(serverServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceListRunEventsHandler := connect.NewUnaryHandler(
		ServerServiceListRunEventsProcedure,
		svc.ListRunEvents,
		connect.WithSchema(serverServiceMethods.ByName("ListRunEvents")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceWatchRunHandler := connect.NewServerStreamHandler(
		ServerServiceWatchRunProcedure,
		svc.WatchRun,
		connect.WithSchema(serverServiceMethods.ByName("WatchRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceStopRunHandler := connect.NewUnaryHandler(
		ServerServiceStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(serverServiceMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServicePauseRunHandler := connect.NewUnaryHandler(
		ServerServicePauseRunProcedure,
		svc.PauseRun,
		connect.WithSchema(serverServiceMethods.ByName("PauseRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceResumeRunHandler := connect.NewUnaryHandler(
		ServerServiceResumeRunProcedure,
		svc.ResumeRun,
		connect.WithSchema(serverServiceMethods.ByName("ResumeRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceInspectRunHandler := connect.NewUnaryHandler(
		ServerServiceInspectRunProcedure,
		svc.InspectRun,
		connect.WithSchema(serverServiceMethods.ByName("InspectRun")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceSubmitWorkflowAssignmentHandler := connect.NewUnaryHandler(
		ServerServiceSubmitWorkflowAssignmentProcedure,
		svc.SubmitWorkflowAssignment,
		connect.WithSchema(serverServiceMethods.ByName("SubmitWorkflowAssignment")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetAssignmentDispositionHandler := connect.NewUnaryHandler(
		ServerServiceGetAssignmentDispositionProcedure,
		svc.GetAssignmentDisposition,
		connect.WithSchema(serverServiceMethods.ByName("GetAssignmentDisposition")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceSendPromptHandler := connect.NewUnaryHandler(
		ServerServiceSendPromptProcedure,
		svc.SendPrompt,
		connect.WithSchema(serverServiceMethods.ByName("SendPrompt")),
		connect.WithHandlerOptions(opts...),
	)
	return "/criteria.v1.ServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerServiceListAgentsProcedure:
			serverServiceListAgentsHandler.ServeHTTP(w, r)
		case ServerServiceGetAgentProcedure:
			serverServiceGetAgentHandler.ServeHTTP(w, r)
		case ServerServiceListRunsProcedure:
			serverServiceListRunsHandler.ServeHTTP(w, r)
		case ServerServiceGetRunProcedure:
			serverServiceGetRunHandler.ServeHTTP(w, r)
		case ServerServiceListRunEventsProcedure:
			serverServiceListRunEventsHandler.ServeHTTP(w, r)
		case ServerServiceWatchRunProcedure:
			serverServiceWatchRunHandler.ServeHTTP(w, r)
		case ServerServiceStopRunProcedure:
			serverServiceStopRunHandler.ServeHTTP(w, r)
		case ServerServicePauseRunProcedure:
			serverServicePauseRunHandler.ServeHTTP(w, r)
		case ServerServiceResumeRunProcedure:
			serverServiceResumeRunHandler.ServeHTTP(w, r)
		case ServerServiceInspectRunProcedure:
			serverServiceInspectRunHandler.ServeHTTP(w, r)
		case ServerServiceSubmitWorkflowAssignmentProcedure:
			serverServiceSubmitWorkflowAssignmentHandler.ServeHTTP(w, r)
		case ServerServiceGetAssignmentDispositionProcedure:
			serverServiceGetAssignmentDispositionHandler.ServeHTTP(w, r)
		case ServerServiceSendPromptProcedure:
			serverServiceSendPromptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerServiceHandler struct{}

func (UnimplementedServerServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.ListAgents is not implemented"))
}

func (UnimplementedServerServiceHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.GetAgent is not implemented"))
}

func (UnimplementedServerServiceHandler) ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.ListRuns is not implemented"))
}

func (UnimplementedServerServiceHandler) GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.GetRun is not implemented"))
}

func (UnimplementedServerServiceHandler) ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.ListRunEvents is not implemented"))
}

func (UnimplementedServerServiceHandler) WatchRun(context.Context, *connect.Request[v1.WatchRunRequest], *connect.ServerStream[v1.Envelope]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.WatchRun is not implemented"))
}

func (UnimplementedServerServiceHandler) StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.StopRun is not implemented"))
}

func (UnimplementedServerServiceHandler) PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.PauseRun is not implemented"))
}

func (UnimplementedServerServiceHandler) ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.ResumeRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.ResumeRun is not implemented"))
}

func (UnimplementedServerServiceHandler) InspectRun(context.Context, *connect.Request[v1.InspectRunRequest]) (*connect.Response[v1.InspectRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.InspectRun is not implemented"))
}

func (UnimplementedServerServiceHandler) SubmitWorkflowAssignment(context.Context, *connect.Request[v1.SubmitWorkflowAssignmentRequest]) (*connect.Response[v1.SubmitWorkflowAssignmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.SubmitWorkflowAssignment is not implemented"))
}

func (UnimplementedServerServiceHandler) GetAssignmentDisposition(context.Context, *connect.Request[v1.GetAssignmentDispositionRequest]) (*connect.Response[v1.GetAssignmentDispositionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.GetAssignmentDisposition is not implemented"))
}

func (UnimplementedServerServiceHandler) SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.ServerService.SendPrompt is not implemented"))
}
