// CriteriaService — RPCs served by the server and consumed by Criteria agents.
//
// Authentication: all RPCs except `Register` require a token (Bearer header,
// `X-Criteria-Token` header, or `criteria-token` Connect metadata). Tokens are
// SHA-256 compared against `criteria.token_hash` in the orchestrator store.
//
// Caller ownership: mutating RPCs enforce that the authenticated caller owns
// the affected criteria agent or run. Implementations MUST enforce this contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: criteria/v1/criteria.proto

package criteriav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Friendly name for the Criteria agent instance.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Free-form labels (e.g. "host=laptop", "os=darwin").
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	// One-time token. Clients should persist this securely and send it on all
	// subsequent RPCs.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Bootstrap credentials supplied by the orchestrator for the registering
	// agent. Agents MAY use these to authenticate to deployment-specific
	// services (e.g. private OCI registries). Keys and semantics are
	// deployment-defined; values are sensitive and MUST be handled securely.
	BootstrapCredentials map[string]string `protobuf:"bytes,3,rep,name=bootstrap_credentials,json=bootstrapCredentials,proto3" json:"bootstrap_credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetBootstrapCredentials() map[string]string {
	if x != nil {
		return x.BootstrapCredentials
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type CreateRunRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId   string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	WorkflowName string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	// Hash of the compiled workflow; used by the server for de-duplication/tracing.
	WorkflowHash string `protobuf:"bytes,3,opt,name=workflow_hash,json=workflowHash,proto3" json:"workflow_hash,omitempty"`
	// Ticket identifier this run backs (e.g. a Linear issue key). When set,
	// CreateRun is idempotent per caller: while an open (non-terminal) run for
	// the same ticket exists, re-creating returns that run unchanged. Used by
	// k8s-native run publishers (CRI-131).
	Ticket string `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// Source repository URL the run operates on.
	RepoUrl       string `protobuf:"bytes,5,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRunRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowHash() string {
	if x != nil {
		return x.WorkflowHash
	}
	return ""
}

func (x *CreateRunRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *CreateRunRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

// Run is the persisted record of a run (mirrors Phase 0 REST DTO).
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CriteriaId    string                 `protobuf:"bytes,2,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	WorkflowHash  string                 `protobuf:"bytes,4,opt,name=workflow_hash,json=workflowHash,proto3" json:"workflow_hash,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "running" | "succeeded" | "failed" | "cancelled"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	FinalState    string                 `protobuf:"bytes,9,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	FailureReason string                 `protobuf:"bytes,10,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// Ticket identifier backing the run, when ticket-backed (k8s-native runs).
	Ticket string `protobuf:"bytes,11,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// Source repository URL.
	RepoUrl string `protobuf:"bytes,12,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// Pull request URL once the run has produced one.
	PrUrl         string `protobuf:"bytes,13,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{5}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *Run) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *Run) GetWorkflowHash() string {
	if x != nil {
		return x.WorkflowHash
	}
	return ""
}

func (x *Run) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Run) GetFinalState() string {
	if x != nil {
		return x.FinalState
	}
	return ""
}

func (x *Run) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Run) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *Run) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Run) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

// ReattachRunRequest is sent by a Criteria agent on startup to query the state of
// a run it believes was in-flight before a crash.
type ReattachRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CriteriaId    string                 `protobuf:"bytes,2,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachRunRequest) Reset() {
	*x = ReattachRunRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachRunRequest) ProtoMessage() {}

func (x *ReattachRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachRunRequest.ProtoReflect.Descriptor instead.
func (*ReattachRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{6}
}

func (x *ReattachRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReattachRunRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

// ReattachRunResponse tells the agent whether it may resume a run.
type ReattachRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status of the run: "running" | "paused" | "succeeded" | "failed" | "cancelled".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Empty when the run is terminal.
	CurrentStep string `protobuf:"bytes,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	// Last started attempt for current_step. 0 if no attempt has been recorded.
	Attempt int32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Last persisted envelope seq for the run.
	LastSeq uint64 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// Server's judgment: false when the run is terminal or belongs to a different
	// criteria agent.
	CanResume bool `protobuf:"varint,5,opt,name=can_resume,json=canResume,proto3" json:"can_resume,omitempty"`
	// JSON-encoded variable scope snapshot at the time of the last persisted
	// StepOutputCaptured or VariableSet event. Empty string means no scope has
	// been persisted yet. Field is permanent (W04).
	VariableScope string `protobuf:"bytes,6,opt,name=variable_scope,json=variableScope,proto3" json:"variable_scope,omitempty"` // permanent (W04)
	// pending_signal is the signal name the run is waiting for when status="paused".
	// The agent must re-enter the wait/approval node with this value set in
	// RunState so it immediately re-issues ErrPaused (waiting for the signal
	// to arrive via Resume). Empty when not paused. Permanent (W05).
	PendingSignal string `protobuf:"bytes,7,opt,name=pending_signal,json=pendingSignal,proto3" json:"pending_signal,omitempty"` // permanent (W05)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachRunResponse) Reset() {
	*x = ReattachRunResponse{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachRunResponse) ProtoMessage() {}

func (x *ReattachRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachRunResponse.ProtoReflect.Descriptor instead.
func (*ReattachRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{7}
}

func (x *ReattachRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReattachRunResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *ReattachRunResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReattachRunResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ReattachRunResponse) GetCanResume() bool {
	if x != nil {
		return x.CanResume
	}
	return false
}

func (x *ReattachRunResponse) GetVariableScope() string {
	if x != nil {
		return x.VariableScope
	}
	return ""
}

func (x *ReattachRunResponse) GetPendingSignal() string {
	if x != nil {
		return x.PendingSignal
	}
	return ""
}

// Ack is the server's reply on SubmitEvents. One Ack per persisted Envelope.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ControlSubscribeRequest is the single message a Criteria agent sends to open the
// Control server-stream.
type ControlSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSubscribeRequest) Reset() {
	*x = ControlSubscribeRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSubscribeRequest) ProtoMessage() {}

func (x *ControlSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSubscribeRequest.ProtoReflect.Descriptor instead.
func (*ControlSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{9}
}

func (x *ControlSubscribeRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

// ControlMessage is a command from the orchestrator to a connected Criteria agent.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlMessage_RunCancel
	//	*ControlMessage_AgentPrompt
	//	*ControlMessage_ControlReady
	//	*ControlMessage_ResumeRun
	//	*ControlMessage_WorkflowAssignment
	//	*ControlMessage_PauseRun
	Command       isControlMessage_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{10}
}

func (x *ControlMessage) GetCommand() isControlMessage_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlMessage) GetRunCancel() *RunCancel {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_RunCancel); ok {
			return x.RunCancel
		}
	}
	return nil
}

func (x *ControlMessage) GetAgentPrompt() *AgentPrompt {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_AgentPrompt); ok {
			return x.AgentPrompt
		}
	}
	return nil
}

func (x *ControlMessage) GetControlReady() *ControlReady {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_ControlReady); ok {
			return x.ControlReady
		}
	}
	return nil
}

func (x *ControlMessage) GetResumeRun() *ResumeRun {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_ResumeRun); ok {
			return x.ResumeRun
		}
	}
	return nil
}

func (x *ControlMessage) GetWorkflowAssignment() *WorkflowAssignment {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_WorkflowAssignment); ok {
			return x.WorkflowAssignment
		}
	}
	return nil
}

func (x *ControlMessage) GetPauseRun() *PauseRun {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_PauseRun); ok {
			return x.PauseRun
		}
	}
	return nil
}

type isControlMessage_Command interface {
	isControlMessage_Command()
}

type ControlMessage_RunCancel struct {
	RunCancel *RunCancel `protobuf:"bytes,1,opt,name=run_cancel,json=runCancel,proto3,oneof"`
}

type ControlMessage_AgentPrompt struct {
	AgentPrompt *AgentPrompt `protobuf:"bytes,2,opt,name=agent_prompt,json=agentPrompt,proto3,oneof"` // Phase 2.3; stub in 1.1.
}

type ControlMessage_ControlReady struct {
	// ControlReady is sent once, immediately after the server accepts the
	// Control subscription. It flushes the response headers so the Connect
	// client's call returns to the caller, and signals that subsequent
	// ControlMessages can be delivered. Clients must ignore it.
	ControlReady *ControlReady `protobuf:"bytes,3,opt,name=control_ready,json=controlReady,proto3,oneof"`
}

type ControlMessage_ResumeRun struct {
	// ResumeRun delivers a resume signal from the orchestrator to the Criteria agent
	// that owns the run. The agent should re-enter the paused node with the
	// supplied payload. Permanent (W05).
	ResumeRun *ResumeRun `protobuf:"bytes,4,opt,name=resume_run,json=resumeRun,proto3,oneof"` // permanent (W05)
}

type ControlMessage_WorkflowAssignment struct {
	// WorkflowAssignment pushes a queued workflow to a long-lived agent.
	// The agent compiles the supplied source and executes it under the provided
	// run_id. The orchestrator is the source of run ids; the agent does not call
	// CreateRun for assignments. Accepted implicitly when the agent starts the
	// run and submits a RunStarted event.
	WorkflowAssignment *WorkflowAssignment `protobuf:"bytes,5,opt,name=workflow_assignment,json=workflowAssignment,proto3,oneof"` // CRI-60
}

type ControlMessage_PauseRun struct {
	// PauseRun asks the Criteria agent to pause an in-flight run. The agent
	// should preserve adapter/run state and enter a paused state.
	PauseRun *PauseRun `protobuf:"bytes,6,opt,name=pause_run,json=pauseRun,proto3,oneof"` // CRI-74
}

func (*ControlMessage_RunCancel) isControlMessage_Command() {}

func (*ControlMessage_AgentPrompt) isControlMessage_Command() {}

func (*ControlMessage_ControlReady) isControlMessage_Command() {}

func (*ControlMessage_ResumeRun) isControlMessage_Command() {}

func (*ControlMessage_WorkflowAssignment) isControlMessage_Command() {}

func (*ControlMessage_PauseRun) isControlMessage_Command() {}

// PauseRun asks the Criteria agent to pause an in-flight run.
type PauseRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRun) Reset() {
	*x = PauseRun{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRun) ProtoMessage() {}

func (x *PauseRun) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRun.ProtoReflect.Descriptor instead.
func (*PauseRun) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{11}
}

func (x *PauseRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PauseRun) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WorkflowAssignment delivers a queued workflow from the orchestrator to a
// long-lived Criteria agent (CRI-60). The agent executes the workflow with
// run_id as the run identity and reports progress via SubmitEvents.
type WorkflowAssignment struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RunId        string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	// workflow_source is the raw HCL/CHCL source for the workflow module.
	WorkflowSource string `protobuf:"bytes,3,opt,name=workflow_source,json=workflowSource,proto3" json:"workflow_source,omitempty"`
	// Optional key/value labels passed through from the orchestrator queue.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// lockfile_source is the optional raw HCL source of the workflow tree's
	// .criteria.lock.hcl. When present the agent writes it next to the workflow
	// source so adapter pins and digests are available during compilation.
	LockfileSource string `protobuf:"bytes,5,opt,name=lockfile_source,json=lockfileSource,proto3" json:"lockfile_source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowAssignment) Reset() {
	*x = WorkflowAssignment{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowAssignment) ProtoMessage() {}

func (x *WorkflowAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowAssignment.ProtoReflect.Descriptor instead.
func (*WorkflowAssignment) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowAssignment) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *WorkflowAssignment) GetWorkflowSource() string {
	if x != nil {
		return x.WorkflowSource
	}
	return ""
}

func (x *WorkflowAssignment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkflowAssignment) GetLockfileSource() string {
	if x != nil {
		return x.LockfileSource
	}
	return ""
}

// RunCancel asks the Criteria agent to cancel an in-flight run.
type RunCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCancel) Reset() {
	*x = RunCancel{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCancel) ProtoMessage() {}

func (x *RunCancel) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCancel.ProtoReflect.Descriptor instead.
func (*RunCancel) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{13}
}

func (x *RunCancel) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AgentPrompt forwards a user prompt to a running agent step. Phase 2.3.
type AgentPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPrompt) Reset() {
	*x = AgentPrompt{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPrompt) ProtoMessage() {}

func (x *AgentPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPrompt.ProtoReflect.Descriptor instead.
func (*AgentPrompt) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{14}
}

func (x *AgentPrompt) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentPrompt) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *AgentPrompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// ControlReady is an attach acknowledgement sent once at stream start.
// It carries no payload.
type ControlReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlReady) Reset() {
	*x = ControlReady{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReady) ProtoMessage() {}

func (x *ControlReady) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReady.ProtoReflect.Descriptor instead.
func (*ControlReady) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{15}
}

// ResumeRun delivers a resume signal from the orchestrator to the Criteria agent (W05).
// The agent should re-enter the paused wait/approval node with the supplied
// payload and continue execution.
type ResumeRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// signal matches the run's pending_signal; the agent should verify this.
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// payload carries decision metadata (e.g. {"decision":"approved","actor":"alice"}).
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRun) Reset() {
	*x = ResumeRun{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRun) ProtoMessage() {}

func (x *ResumeRun) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRun.ProtoReflect.Descriptor instead.
func (*ResumeRun) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResumeRun) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ResumeRun) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ResumeRequest delivers a named signal (or an approval decision) to a paused
// run. This message is SDK contract surface: avoid orchestrator-specific names.
type ResumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// signal is the name of the pending signal to satisfy. For wait nodes with
	// signal=<name> this is that signal name. For approval nodes this is the
	// approval node name.
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// payload carries optional key/value metadata.
	// For approval: payload["decision"] = "approved" | "rejected"
	//
	//	payload["actor"]    = identity of approver (audit metadata).
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResumeRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ResumeRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ResumeResponse reports whether the Resume RPC was accepted.
type ResumeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason is one of: "ok" | "run_not_paused" | "signal_mismatch" | "no_pending_signal"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_criteria_v1_criteria_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_criteria_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_criteria_proto_rawDescGZIP(), []int{18}
}

func (x *ResumeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResumeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_criteria_v1_criteria_proto protoreflect.FileDescriptor

const file_criteria_v1_criteria_proto_rawDesc = "" +
	"\n" +
	"\x1acriteria/v1/criteria.proto\x12\vcriteria.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18criteria/v1/events.proto\"\xa2\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\x06labels\x18\x02 \x03(\v2(.criteria.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12l\n" +
	"\x15bootstrap_credentials\x18\x03 \x03(\v27.criteria.v1.RegisterResponse.BootstrapCredentialsEntryR\x14bootstrapCredentials\x1aG\n" +
	"\x19BootstrapCredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\"P\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb0\x01\n" +
	"\x10CreateRunRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12#\n" +
	"\rworkflow_hash\x18\x03 \x01(\tR\fworkflowHash\x12\x16\n" +
	"\x06ticket\x18\x04 \x01(\tR\x06ticket\x12\x19\n" +
	"\brepo_url\x18\x05 \x01(\tR\arepoUrl\"\xde\x03\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vcriteria_id\x18\x02 \x01(\tR\n" +
	"criteriaId\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x12#\n" +
	"\rworkflow_hash\x18\x04 \x01(\tR\fworkflowHash\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1f\n" +
	"\vfinal_state\x18\t \x01(\tR\n" +
	"finalState\x12%\n" +
	"\x0efailure_reason\x18\n" +
	" \x01(\tR\rfailureReason\x12\x16\n" +
	"\x06ticket\x18\v \x01(\tR\x06ticket\x12\x19\n" +
	"\brepo_url\x18\f \x01(\tR\arepoUrl\x12\x15\n" +
	"\x06pr_url\x18\r \x01(\tR\x05prUrl\"L\n" +
	"\x12ReattachRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vcriteria_id\x18\x02 \x01(\tR\n" +
	"criteriaId\"\xf2\x01\n" +
	"\x13ReattachRunResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\tR\vcurrentStep\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\x04R\alastSeq\x12\x1d\n" +
	"\n" +
	"can_resume\x18\x05 \x01(\bR\tcanResume\x12%\n" +
	"\x0evariable_scope\x18\x06 \x01(\tR\rvariableScope\x12%\n" +
	"\x0epending_signal\x18\a \x01(\tR\rpendingSignal\"U\n" +
	"\x03Ack\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\":\n" +
	"\x17ControlSubscribeRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\"\x98\x03\n" +
	"\x0eControlMessage\x127\n" +
	"\n" +
	"run_cancel\x18\x01 \x01(\v2\x16.criteria.v1.RunCancelH\x00R\trunCancel\x12=\n" +
	"\fagent_prompt\x18\x02 \x01(\v2\x18.criteria.v1.AgentPromptH\x00R\vagentPrompt\x12@\n" +
	"\rcontrol_ready\x18\x03 \x01(\v2\x19.criteria.v1.ControlReadyH\x00R\fcontrolReady\x127\n" +
	"\n" +
	"resume_run\x18\x04 \x01(\v2\x16.criteria.v1.ResumeRunH\x00R\tresumeRun\x12R\n" +
	"\x13workflow_assignment\x18\x05 \x01(\v2\x1f.criteria.v1.WorkflowAssignmentH\x00R\x12workflowAssignment\x124\n" +
	"\tpause_run\x18\x06 \x01(\v2\x15.criteria.v1.PauseRunH\x00R\bpauseRunB\t\n" +
	"\acommand\"9\n" +
	"\bPauseRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa2\x02\n" +
	"\x12WorkflowAssignment\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12'\n" +
	"\x0fworkflow_source\x18\x03 \x01(\tR\x0eworkflowSource\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.criteria.v1.WorkflowAssignment.LabelsEntryR\x06labels\x12'\n" +
	"\x0flockfile_source\x18\x05 \x01(\tR\x0elockfileSource\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\tRunCancel\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\vAgentPrompt\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"\x0e\n" +
	"\fControlReady\"\xb5\x01\n" +
	"\tResumeRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12=\n" +
	"\apayload\x18\x03 \x03(\v2#.criteria.v1.ResumeRun.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\rResumeRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12A\n" +
	"\apayload\x18\x03 \x03(\v2'.criteria.v1.ResumeRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eResumeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x86\x04\n" +
	"\x0fCriteriaService\x12G\n" +
	"\bRegister\x12\x1c.criteria.v1.RegisterRequest\x1a\x1d.criteria.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.criteria.v1.HeartbeatRequest\x1a\x1e.criteria.v1.HeartbeatResponse\x12<\n" +
	"\tCreateRun\x12\x1d.criteria.v1.CreateRunRequest\x1a\x10.criteria.v1.Run\x12P\n" +
	"\vReattachRun\x12\x1f.criteria.v1.ReattachRunRequest\x1a .criteria.v1.ReattachRunResponse\x12A\n" +
	"\x06Resume\x12\x1a.criteria.v1.ResumeRequest\x1a\x1b.criteria.v1.ResumeResponse\x12;\n" +
	"\fSubmitEvents\x12\x15.criteria.v1.Envelope\x1a\x10.criteria.v1.Ack(\x010\x01\x12N\n" +
	"\aControl\x12$.criteria.v1.ControlSubscribeRequest\x1a\x1b.criteria.v1.ControlMessage0\x01BaZ_github.com/brokenbots/workflow-example/criteria-k8s/internal/criteria/pb/criteria/v1;criteriav1b\x06proto3"

var (
	file_criteria_v1_criteria_proto_rawDescOnce sync.Once
	file_criteria_v1_criteria_proto_rawDescData []byte
)

func file_criteria_v1_criteria_proto_rawDescGZIP() []byte {
	file_criteria_v1_criteria_proto_rawDescOnce.Do(func() {
		file_criteria_v1_criteria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v1_criteria_proto_rawDesc), len(file_criteria_v1_criteria_proto_rawDesc)))
	})
	return file_criteria_v1_criteria_proto_rawDescData
}

var file_criteria_v1_criteria_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_criteria_v1_criteria_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: criteria.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 1: criteria.v1.RegisterResponse
	(*HeartbeatRequest)(nil),        // 2: criteria.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: criteria.v1.HeartbeatResponse
	(*CreateRunRequest)(nil),        // 4: criteria.v1.CreateRunRequest
	(*Run)(nil),                     // 5: criteria.v1.Run
	(*ReattachRunRequest)(nil),      // 6: criteria.v1.ReattachRunRequest
	(*ReattachRunResponse)(nil),     // 7: criteria.v1.ReattachRunResponse
	(*Ack)(nil),                     // 8: criteria.v1.Ack
	(*ControlSubscribeRequest)(nil), // 9: criteria.v1.ControlSubscribeRequest
	(*ControlMessage)(nil),          // 10: criteria.v1.ControlMessage
	(*PauseRun)(nil),                // 11: criteria.v1.PauseRun
	(*WorkflowAssignment)(nil),      // 12: criteria.v1.WorkflowAssignment
	(*RunCancel)(nil),               // 13: criteria.v1.RunCancel
	(*AgentPrompt)(nil),             // 14: criteria.v1.AgentPrompt
	(*ControlReady)(nil),            // 15: criteria.v1.ControlReady
	(*ResumeRun)(nil),               // 16: criteria.v1.ResumeRun
	(*ResumeRequest)(nil),           // 17: criteria.v1.ResumeRequest
	(*ResumeResponse)(nil),          // 18: criteria.v1.ResumeResponse
	nil,                             // 19: criteria.v1.RegisterRequest.LabelsEntry
	nil,                             // 20: criteria.v1.RegisterResponse.BootstrapCredentialsEntry
	nil,                             // 21: criteria.v1.WorkflowAssignment.LabelsEntry
	nil,                             // 22: criteria.v1.ResumeRun.PayloadEntry
	nil,                             // 23: criteria.v1.ResumeRequest.PayloadEntry
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
	(*Envelope)(nil),                // 25: criteria.v1.Envelope
}
var file_criteria_v1_criteria_proto_depIdxs = []int32{
	19, // 0: criteria.v1.RegisterRequest.labels:type_name -> criteria.v1.RegisterRequest.LabelsEntry
	20, // 1: criteria.v1.RegisterResponse.bootstrap_credentials:type_name -> criteria.v1.RegisterResponse.BootstrapCredentialsEntry
	24, // 2: criteria.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	24, // 3: criteria.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: criteria.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	24, // 5: criteria.v1.Run.ended_at:type_name -> google.protobuf.Timestamp
	13, // 6: criteria.v1.ControlMessage.run_cancel:type_name -> criteria.v1.RunCancel
	14, // 7: criteria.v1.ControlMessage.agent_prompt:type_name -> criteria.v1.AgentPrompt
	15, // 8: criteria.v1.ControlMessage.control_ready:type_name -> criteria.v1.ControlReady
	16, // 9: criteria.v1.ControlMessage.resume_run:type_name -> criteria.v1.ResumeRun
	12, // 10: criteria.v1.ControlMessage.workflow_assignment:type_name -> criteria.v1.WorkflowAssignment
	11, // 11: criteria.v1.ControlMessage.pause_run:type_name -> criteria.v1.PauseRun
	21, // 12: criteria.v1.WorkflowAssignment.labels:type_name -> criteria.v1.WorkflowAssignment.LabelsEntry
	22, // 13: criteria.v1.ResumeRun.payload:type_name -> criteria.v1.ResumeRun.PayloadEntry
	23, // 14: criteria.v1.ResumeRequest.payload:type_name -> criteria.v1.ResumeRequest.PayloadEntry
	0,  // 15: criteria.v1.CriteriaService.Register:input_type -> criteria.v1.RegisterRequest
	2,  // 16: criteria.v1.CriteriaService.Heartbeat:input_type -> criteria.v1.HeartbeatRequest
	4,  // 17: criteria.v1.CriteriaService.CreateRun:input_type -> criteria.v1.CreateRunRequest
	6,  // 18: criteria.v1.CriteriaService.ReattachRun:input_type -> criteria.v1.ReattachRunRequest
	17, // 19: criteria.v1.CriteriaService.Resume:input_type -> criteria.v1.ResumeRequest
	25, // 20: criteria.v1.CriteriaService.SubmitEvents:input_type -> criteria.v1.Envelope
	9,  // 21: criteria.v1.CriteriaService.Control:input_type -> criteria.v1.ControlSubscribeRequest
	1,  // 22: criteria.v1.CriteriaService.Register:output_type -> criteria.v1.RegisterResponse
	3,  // 23: criteria.v1.CriteriaService.Heartbeat:output_type -> criteria.v1.HeartbeatResponse
	5,  // 24: criteria.v1.CriteriaService.CreateRun:output_type -> criteria.v1.Run
	7,  // 25: criteria.v1.CriteriaService.ReattachRun:output_type -> criteria.v1.ReattachRunResponse
	18, // 26: criteria.v1.CriteriaService.Resume:output_type -> criteria.v1.ResumeResponse
	8,  // 27: criteria.v1.CriteriaService.SubmitEvents:output_type -> criteria.v1.Ack
	10, // 28: criteria.v1.CriteriaService.Control:output_type -> criteria.v1.ControlMessage
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_criteria_v1_criteria_proto_init() }
func file_criteria_v1_criteria_proto_init() {
	if File_criteria_v1_criteria_proto != nil {
		return
	}
	file_criteria_v1_events_proto_init()
	file_criteria_v1_criteria_proto_msgTypes[10].OneofWrappers = []any{
		(*ControlMessage_RunCancel)(nil),
		(*ControlMessage_AgentPrompt)(nil),
		(*ControlMessage_ControlReady)(nil),
		(*ControlMessage_ResumeRun)(nil),
		(*ControlMessage_WorkflowAssignment)(nil),
		(*ControlMessage_PauseRun)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v1_criteria_proto_rawDesc), len(file_criteria_v1_criteria_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v1_criteria_proto_goTypes,
		DependencyIndexes: file_criteria_v1_criteria_proto_depIdxs,
		MessageInfos:      file_criteria_v1_criteria_proto_msgTypes,
	}.Build()
	File_criteria_v1_criteria_proto = out.File
	file_criteria_v1_criteria_proto_goTypes = nil
	file_criteria_v1_criteria_proto_depIdxs = nil
}
