// ServerService — read/control RPCs served by the server and consumed by UI clients
// (and any human tooling such as grpcurl).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: criteria/v1/server.proto

package criteriav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkflowAssignmentState enumerates the possible states of an operator-
// submitted workflow assignment. The assignment lifecycle is independent of
// the run lifecycle: an assignment moves through queued -> leased, and may
// end in terminal or rejected. The run itself progresses via events on the
// agent Control stream.
type WorkflowAssignmentState int32

const (
	WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED WorkflowAssignmentState = 0
	// QUEUED — the assignment is waiting for an agent to lease it.
	WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_QUEUED WorkflowAssignmentState = 1
	// LEASED — an agent has leased the assignment and is executing the run.
	// This state covers both "leased" and "running" from the operator
	// perspective.
	WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_LEASED WorkflowAssignmentState = 2
	// TERMINAL — the run reached a terminal state, or the assignment was
	// accepted and later ended (completed, failed, cancelled). The assignment
	// is no longer active.
	WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_TERMINAL WorkflowAssignmentState = 3
	// REJECTED — the assignment was rejected immediately upon submission
	// (invalid source, no matching agent, policy failure, etc.). No run was
	// created.
	WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_REJECTED WorkflowAssignmentState = 4
)

// Enum value maps for WorkflowAssignmentState.
var (
	WorkflowAssignmentState_name = map[int32]string{
		0: "WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED",
		1: "WORKFLOW_ASSIGNMENT_STATE_QUEUED",
		2: "WORKFLOW_ASSIGNMENT_STATE_LEASED",
		3: "WORKFLOW_ASSIGNMENT_STATE_TERMINAL",
		4: "WORKFLOW_ASSIGNMENT_STATE_REJECTED",
	}
	WorkflowAssignmentState_value = map[string]int32{
		"WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED": 0,
		"WORKFLOW_ASSIGNMENT_STATE_QUEUED":      1,
		"WORKFLOW_ASSIGNMENT_STATE_LEASED":      2,
		"WORKFLOW_ASSIGNMENT_STATE_TERMINAL":    3,
		"WORKFLOW_ASSIGNMENT_STATE_REJECTED":    4,
	}
)

func (x WorkflowAssignmentState) Enum() *WorkflowAssignmentState {
	p := new(WorkflowAssignmentState)
	*p = x
	return p
}

func (x WorkflowAssignmentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowAssignmentState) Descriptor() protoreflect.EnumDescriptor {
	return file_criteria_v1_server_proto_enumTypes[0].Descriptor()
}

func (WorkflowAssignmentState) Type() protoreflect.EnumType {
	return &file_criteria_v1_server_proto_enumTypes[0]
}

func (x WorkflowAssignmentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowAssignmentState.Descriptor instead.
func (WorkflowAssignmentState) EnumDescriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{0}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" | "offline"
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_criteria_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Agent) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *ListRunsRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *ListRunsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"` // exclusive
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsRequest) Reset() {
	*x = ListRunEventsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsRequest) ProtoMessage() {}

func (x *ListRunEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRunEventsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *ListRunEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListRunEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *ListRunEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunEventsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Events  []*Envelope            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	LastSeq uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// Continuation cursor. When set, pass this as since_seq in the next call.
	NextSinceSeq  uint64 `protobuf:"varint,3,opt,name=next_since_seq,json=nextSinceSeq,proto3" json:"next_since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsResponse) Reset() {
	*x = ListRunEventsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsResponse) ProtoMessage() {}

func (x *ListRunEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsResponse.ProtoReflect.Descriptor instead.
func (*ListRunEventsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *ListRunEventsResponse) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListRunEventsResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ListRunEventsResponse) GetNextSinceSeq() uint64 {
	if x != nil {
		return x.NextSinceSeq
	}
	return 0
}

type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`            // exclusive; 0 streams from the beginning
	SubscriberId  string                 `protobuf:"bytes,3,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"` // optional durable cursor key scoped by run_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *WatchRunRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *StopRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ServerTime when the cancel was issued; the run may still take time to
	// observe and react to the cancel.
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *StopRunResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type PauseRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunRequest) Reset() {
	*x = PauseRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunRequest) ProtoMessage() {}

func (x *PauseRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunRequest.ProtoReflect.Descriptor instead.
func (*PauseRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *PauseRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type PauseRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunResponse) Reset() {
	*x = PauseRunResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunResponse) ProtoMessage() {}

func (x *PauseRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunResponse.ProtoReflect.Descriptor instead.
func (*PauseRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *PauseRunResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type ResumeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunRequest) Reset() {
	*x = ResumeRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunRequest) ProtoMessage() {}

func (x *ResumeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunRequest.ProtoReflect.Descriptor instead.
func (*ResumeRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ResumeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunResponse) Reset() {
	*x = ResumeRunResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunResponse) ProtoMessage() {}

func (x *ResumeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunResponse.ProtoReflect.Descriptor instead.
func (*ResumeRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeRunResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type InspectRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // optional; if empty the server may return a summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRunRequest) Reset() {
	*x = InspectRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRunRequest) ProtoMessage() {}

func (x *InspectRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRunRequest.ProtoReflect.Descriptor instead.
func (*InspectRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *InspectRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InspectRunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InspectRunResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Adapter            string                 `protobuf:"bytes,3,opt,name=adapter,proto3" json:"adapter,omitempty"`
	CurrentStep        string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	PendingPermissions int64                  `protobuf:"varint,5,opt,name=pending_permissions,json=pendingPermissions,proto3" json:"pending_permissions,omitempty"`
	LastActivityAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	// Opaque adapter state — the host pretty-prints any well-formed JSON.
	StateJson     string `protobuf:"bytes,7,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRunResponse) Reset() {
	*x = InspectRunResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRunResponse) ProtoMessage() {}

func (x *InspectRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRunResponse.ProtoReflect.Descriptor instead.
func (*InspectRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{17}
}

func (x *InspectRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InspectRunResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InspectRunResponse) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *InspectRunResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *InspectRunResponse) GetPendingPermissions() int64 {
	if x != nil {
		return x.PendingPermissions
	}
	return 0
}

func (x *InspectRunResponse) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

func (x *InspectRunResponse) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

type SendPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptRequest) Reset() {
	*x = SendPromptRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptRequest) ProtoMessage() {}

func (x *SendPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptRequest.ProtoReflect.Descriptor instead.
func (*SendPromptRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{18}
}

func (x *SendPromptRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SendPromptRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *SendPromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SendPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptResponse) Reset() {
	*x = SendPromptResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptResponse) ProtoMessage() {}

func (x *SendPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptResponse.ProtoReflect.Descriptor instead.
func (*SendPromptResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{19}
}

func (x *SendPromptResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type SubmitWorkflowAssignmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workflow_name is the logical name of the workflow to execute.
	WorkflowName string `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	// workflow_source is the raw HCL/CHCL source for the workflow module.
	WorkflowSource string `protobuf:"bytes,2,opt,name=workflow_source,json=workflowSource,proto3" json:"workflow_source,omitempty"`
	// lockfile_source is the optional raw HCL source of the workflow tree's
	// .criteria.lock.hcl. When present the agent writes it next to the
	// workflow source so adapter pins and digests are available during
	// compilation.
	LockfileSource string `protobuf:"bytes,3,opt,name=lockfile_source,json=lockfileSource,proto3" json:"lockfile_source,omitempty"`
	// labels are optional key/value pairs used for routing/matching the
	// assignment to an agent. They are also passed through to the executing
	// agent.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// idempotency_key is an optional opaque caller-provided identifier. When
	// non-empty, duplicate submissions with the same key in the same caller
	// scope MUST return the existing run_id and current state without creating
	// a duplicate run or assignment.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitWorkflowAssignmentRequest) Reset() {
	*x = SubmitWorkflowAssignmentRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowAssignmentRequest) ProtoMessage() {}

func (x *SubmitWorkflowAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowAssignmentRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{20}
}

func (x *SubmitWorkflowAssignmentRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *SubmitWorkflowAssignmentRequest) GetWorkflowSource() string {
	if x != nil {
		return x.WorkflowSource
	}
	return ""
}

func (x *SubmitWorkflowAssignmentRequest) GetLockfileSource() string {
	if x != nil {
		return x.LockfileSource
	}
	return ""
}

func (x *SubmitWorkflowAssignmentRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SubmitWorkflowAssignmentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SubmitWorkflowAssignmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id is the server-created run identifier. For idempotent replays this
	// is the run_id of the existing assignment.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// state is the current assignment state.
	State WorkflowAssignmentState `protobuf:"varint,2,opt,name=state,proto3,enum=criteria.v1.WorkflowAssignmentState" json:"state,omitempty"`
	// created_at is the server time when the assignment was first recorded.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When state == REJECTED, a human-readable reason for the rejection.
	RejectionReason string `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// When state == LEASED or TERMINAL, the criteria ID of the agent that
	// leased the assignment, if known.
	LeasedCriteriaId string `protobuf:"bytes,5,opt,name=leased_criteria_id,json=leasedCriteriaId,proto3" json:"leased_criteria_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitWorkflowAssignmentResponse) Reset() {
	*x = SubmitWorkflowAssignmentResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowAssignmentResponse) ProtoMessage() {}

func (x *SubmitWorkflowAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowAssignmentResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{21}
}

func (x *SubmitWorkflowAssignmentResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SubmitWorkflowAssignmentResponse) GetState() WorkflowAssignmentState {
	if x != nil {
		return x.State
	}
	return WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED
}

func (x *SubmitWorkflowAssignmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubmitWorkflowAssignmentResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *SubmitWorkflowAssignmentResponse) GetLeasedCriteriaId() string {
	if x != nil {
		return x.LeasedCriteriaId
	}
	return ""
}

type GetAssignmentDispositionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id is the server-created run identifier returned by
	// SubmitWorkflowAssignment.
	RunId         string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentDispositionRequest) Reset() {
	*x = GetAssignmentDispositionRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentDispositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentDispositionRequest) ProtoMessage() {}

func (x *GetAssignmentDispositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentDispositionRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentDispositionRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{22}
}

func (x *GetAssignmentDispositionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetAssignmentDispositionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id is the server-created run identifier.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// state is the current assignment state.
	State WorkflowAssignmentState `protobuf:"varint,2,opt,name=state,proto3,enum=criteria.v1.WorkflowAssignmentState" json:"state,omitempty"`
	// created_at is the server time when the assignment was first recorded.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the server time of the last assignment state change.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// When state == REJECTED, a human-readable reason for the rejection.
	RejectionReason string `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// When state == LEASED or TERMINAL, the criteria ID of the agent that
	// leased the assignment, if known.
	LeasedCriteriaId string `protobuf:"bytes,6,opt,name=leased_criteria_id,json=leasedCriteriaId,proto3" json:"leased_criteria_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAssignmentDispositionResponse) Reset() {
	*x = GetAssignmentDispositionResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentDispositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentDispositionResponse) ProtoMessage() {}

func (x *GetAssignmentDispositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentDispositionResponse.ProtoReflect.Descriptor instead.
func (*GetAssignmentDispositionResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{23}
}

func (x *GetAssignmentDispositionResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetAssignmentDispositionResponse) GetState() WorkflowAssignmentState {
	if x != nil {
		return x.State
	}
	return WorkflowAssignmentState_WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED
}

func (x *GetAssignmentDispositionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAssignmentDispositionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetAssignmentDispositionResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *GetAssignmentDispositionResponse) GetLeasedCriteriaId() string {
	if x != nil {
		return x.LeasedCriteriaId
	}
	return ""
}

var File_criteria_v1_server_proto protoreflect.FileDescriptor

const file_criteria_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x18criteria/v1/server.proto\x12\vcriteria.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18criteria/v1/events.proto\x1a\x1acriteria/v1/criteria.proto\"\xc6\x02\n" +
	"\x05Agent\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06labels\x18\x03 \x03(\v2\x1e.criteria.v1.Agent.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\flast_seen_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x11ListAgentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"h\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.criteria.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x0fGetAgentRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\"\x7f\n" +
	"\x0fListRunsRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"`\n" +
	"\x10ListRunsResponse\x12$\n" +
	"\x04runs\x18\x01 \x03(\v2\x10.criteria.v1.RunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"`\n" +
	"\x14ListRunEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x87\x01\n" +
	"\x15ListRunEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.criteria.v1.EnvelopeR\x06events\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12$\n" +
	"\x0enext_since_seq\x18\x03 \x01(\x04R\fnextSinceSeq\"j\n" +
	"\x0fWatchRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12#\n" +
	"\rsubscriber_id\x18\x03 \x01(\tR\fsubscriberId\"?\n" +
	"\x0eStopRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x0fStopRunResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"(\n" +
	"\x0fPauseRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"K\n" +
	"\x10PauseRunResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\")\n" +
	"\x10ResumeRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"L\n" +
	"\x11ResumeRunResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"I\n" +
	"\x11InspectRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x9d\x02\n" +
	"\x12InspectRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\aadapter\x18\x03 \x01(\tR\aadapter\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12/\n" +
	"\x13pending_permissions\x18\x05 \x01(\x03R\x12pendingPermissions\x12D\n" +
	"\x10last_activity_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActivityAt\x12\x1d\n" +
	"\n" +
	"state_json\x18\a \x01(\tR\tstateJson\"V\n" +
	"\x11SendPromptRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"M\n" +
	"\x12SendPromptResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"\xce\x02\n" +
	"\x1fSubmitWorkflowAssignmentRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12'\n" +
	"\x0fworkflow_source\x18\x02 \x01(\tR\x0eworkflowSource\x12'\n" +
	"\x0flockfile_source\x18\x03 \x01(\tR\x0elockfileSource\x12P\n" +
	"\x06labels\x18\x04 \x03(\v28.criteria.v1.SubmitWorkflowAssignmentRequest.LabelsEntryR\x06labels\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x02\n" +
	" SubmitWorkflowAssignmentResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.criteria.v1.WorkflowAssignmentStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12,\n" +
	"\x12leased_criteria_id\x18\x05 \x01(\tR\x10leasedCriteriaId\"8\n" +
	"\x1fGetAssignmentDispositionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xc4\x02\n" +
	" GetAssignmentDispositionResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.criteria.v1.WorkflowAssignmentStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\x12,\n" +
	"\x12leased_criteria_id\x18\x06 \x01(\tR\x10leasedCriteriaId*\xe0\x01\n" +
	"\x17WorkflowAssignmentState\x12)\n" +
	"%WORKFLOW_ASSIGNMENT_STATE_UNSPECIFIED\x10\x00\x12$\n" +
	" WORKFLOW_ASSIGNMENT_STATE_QUEUED\x10\x01\x12$\n" +
	" WORKFLOW_ASSIGNMENT_STATE_LEASED\x10\x02\x12&\n" +
	"\"WORKFLOW_ASSIGNMENT_STATE_TERMINAL\x10\x03\x12&\n" +
	"\"WORKFLOW_ASSIGNMENT_STATE_REJECTED\x10\x042\xa3\b\n" +
	"\rServerService\x12M\n" +
	"\n" +
	"ListAgents\x12\x1e.criteria.v1.ListAgentsRequest\x1a\x1f.criteria.v1.ListAgentsResponse\x12<\n" +
	"\bGetAgent\x12\x1c.criteria.v1.GetAgentRequest\x1a\x12.criteria.v1.Agent\x12G\n" +
	"\bListRuns\x12\x1c.criteria.v1.ListRunsRequest\x1a\x1d.criteria.v1.ListRunsResponse\x126\n" +
	"\x06GetRun\x12\x1a.criteria.v1.GetRunRequest\x1a\x10.criteria.v1.Run\x12V\n" +
	"\rListRunEvents\x12!.criteria.v1.ListRunEventsRequest\x1a\".criteria.v1.ListRunEventsResponse\x12A\n" +
	"\bWatchRun\x12\x1c.criteria.v1.WatchRunRequest\x1a\x15.criteria.v1.Envelope0\x01\x12D\n" +
	"\aStopRun\x12\x1b.criteria.v1.StopRunRequest\x1a\x1c.criteria.v1.StopRunResponse\x12G\n" +
	"\bPauseRun\x12\x1c.criteria.v1.PauseRunRequest\x1a\x1d.criteria.v1.PauseRunResponse\x12J\n" +
	"\tResumeRun\x12\x1d.criteria.v1.ResumeRunRequest\x1a\x1e.criteria.v1.ResumeRunResponse\x12M\n" +
	"\n" +
	"InspectRun\x12\x1e.criteria.v1.InspectRunRequest\x1a\x1f.criteria.v1.InspectRunResponse\x12w\n" +
	"\x18SubmitWorkflowAssignment\x12,.criteria.v1.SubmitWorkflowAssignmentRequest\x1a-.criteria.v1.SubmitWorkflowAssignmentResponse\x12w\n" +
	"\x18GetAssignmentDisposition\x12,.criteria.v1.GetAssignmentDispositionRequest\x1a-.criteria.v1.GetAssignmentDispositionResponse\x12M\n" +
	"\n" +
	"SendPrompt\x12\x1e.criteria.v1.SendPromptRequest\x1a\x1f.criteria.v1.SendPromptResponseBaZ_github.com/brokenbots/workflow-example/criteria-k8s/internal/criteria/pb/criteria/v1;criteriav1b\x06proto3"

var (
	file_criteria_v1_server_proto_rawDescOnce sync.Once
	file_criteria_v1_server_proto_rawDescData []byte
)

func file_criteria_v1_server_proto_rawDescGZIP() []byte {
	file_criteria_v1_server_proto_rawDescOnce.Do(func() {
		file_criteria_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v1_server_proto_rawDesc), len(file_criteria_v1_server_proto_rawDesc)))
	})
	return file_criteria_v1_server_proto_rawDescData
}

var file_criteria_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_criteria_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_criteria_v1_server_proto_goTypes = []any{
	(WorkflowAssignmentState)(0),             // 0: criteria.v1.WorkflowAssignmentState
	(*Agent)(nil),                            // 1: criteria.v1.Agent
	(*ListAgentsRequest)(nil),                // 2: criteria.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),               // 3: criteria.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),                  // 4: criteria.v1.GetAgentRequest
	(*ListRunsRequest)(nil),                  // 5: criteria.v1.ListRunsRequest
	(*ListRunsResponse)(nil),                 // 6: criteria.v1.ListRunsResponse
	(*GetRunRequest)(nil),                    // 7: criteria.v1.GetRunRequest
	(*ListRunEventsRequest)(nil),             // 8: criteria.v1.ListRunEventsRequest
	(*ListRunEventsResponse)(nil),            // 9: criteria.v1.ListRunEventsResponse
	(*WatchRunRequest)(nil),                  // 10: criteria.v1.WatchRunRequest
	(*StopRunRequest)(nil),                   // 11: criteria.v1.StopRunRequest
	(*StopRunResponse)(nil),                  // 12: criteria.v1.StopRunResponse
	(*PauseRunRequest)(nil),                  // 13: criteria.v1.PauseRunRequest
	(*PauseRunResponse)(nil),                 // 14: criteria.v1.PauseRunResponse
	(*ResumeRunRequest)(nil),                 // 15: criteria.v1.ResumeRunRequest
	(*ResumeRunResponse)(nil),                // 16: criteria.v1.ResumeRunResponse
	(*InspectRunRequest)(nil),                // 17: criteria.v1.InspectRunRequest
	(*InspectRunResponse)(nil),               // 18: criteria.v1.InspectRunResponse
	(*SendPromptRequest)(nil),                // 19: criteria.v1.SendPromptRequest
	(*SendPromptResponse)(nil),               // 20: criteria.v1.SendPromptResponse
	(*SubmitWorkflowAssignmentRequest)(nil),  // 21: criteria.v1.SubmitWorkflowAssignmentRequest
	(*SubmitWorkflowAssignmentResponse)(nil), // 22: criteria.v1.SubmitWorkflowAssignmentResponse
	(*GetAssignmentDispositionRequest)(nil),  // 23: criteria.v1.GetAssignmentDispositionRequest
	(*GetAssignmentDispositionResponse)(nil), // 24: criteria.v1.GetAssignmentDispositionResponse
	nil,                                      // 25: criteria.v1.Agent.LabelsEntry
	nil,                                      // 26: criteria.v1.SubmitWorkflowAssignmentRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),            // 27: google.protobuf.Timestamp
	(*Run)(nil),                              // 28: criteria.v1.Run
	(*Envelope)(nil),                         // 29: criteria.v1.Envelope
}
var file_criteria_v1_server_proto_depIdxs = []int32{
	25, // 0: criteria.v1.Agent.labels:type_name -> criteria.v1.Agent.LabelsEntry
	27, // 1: criteria.v1.Agent.registered_at:type_name -> google.protobuf.Timestamp
	27, // 2: criteria.v1.Agent.last_seen_at:type_name -> google.protobuf.Timestamp
	1,  // 3: criteria.v1.ListAgentsResponse.agents:type_name -> criteria.v1.Agent
	28, // 4: criteria.v1.ListRunsResponse.runs:type_name -> criteria.v1.Run
	29, // 5: criteria.v1.ListRunEventsResponse.events:type_name -> criteria.v1.Envelope
	27, // 6: criteria.v1.StopRunResponse.issued_at:type_name -> google.protobuf.Timestamp
	27, // 7: criteria.v1.PauseRunResponse.issued_at:type_name -> google.protobuf.Timestamp
	27, // 8: criteria.v1.ResumeRunResponse.issued_at:type_name -> google.protobuf.Timestamp
	27, // 9: criteria.v1.InspectRunResponse.last_activity_at:type_name -> google.protobuf.Timestamp
	27, // 10: criteria.v1.SendPromptResponse.issued_at:type_name -> google.protobuf.Timestamp
	26, // 11: criteria.v1.SubmitWorkflowAssignmentRequest.labels:type_name -> criteria.v1.SubmitWorkflowAssignmentRequest.LabelsEntry
	0,  // 12: criteria.v1.SubmitWorkflowAssignmentResponse.state:type_name -> criteria.v1.WorkflowAssignmentState
	27, // 13: criteria.v1.SubmitWorkflowAssignmentResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 14: criteria.v1.GetAssignmentDispositionResponse.state:type_name -> criteria.v1.WorkflowAssignmentState
	27, // 15: criteria.v1.GetAssignmentDispositionResponse.created_at:type_name -> google.protobuf.Timestamp
	27, // 16: criteria.v1.GetAssignmentDispositionResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 17: criteria.v1.ServerService.ListAgents:input_type -> criteria.v1.ListAgentsRequest
	4,  // 18: criteria.v1.ServerService.GetAgent:input_type -> criteria.v1.GetAgentRequest
	5,  // 19: criteria.v1.ServerService.ListRuns:input_type -> criteria.v1.ListRunsRequest
	7,  // 20: criteria.v1.ServerService.GetRun:input_type -> criteria.v1.GetRunRequest
	8,  // 21: criteria.v1.ServerService.ListRunEvents:input_type -> criteria.v1.ListRunEventsRequest
	10, // 22: criteria.v1.ServerService.WatchRun:input_type -> criteria.v1.WatchRunRequest
	11, // 23: criteria.v1.ServerService.StopRun:input_type -> criteria.v1.StopRunRequest
	13, // 24: criteria.v1.ServerService.PauseRun:input_type -> criteria.v1.PauseRunRequest
	15, // 25: criteria.v1.ServerService.ResumeRun:input_type -> criteria.v1.ResumeRunRequest
	17, // 26: criteria.v1.ServerService.InspectRun:input_type -> criteria.v1.InspectRunRequest
	21, // 27: criteria.v1.ServerService.SubmitWorkflowAssignment:input_type -> criteria.v1.SubmitWorkflowAssignmentRequest
	23, // 28: criteria.v1.ServerService.GetAssignmentDisposition:input_type -> criteria.v1.GetAssignmentDispositionRequest
	19, // 29: criteria.v1.ServerService.SendPrompt:input_type -> criteria.v1.SendPromptRequest
	3,  // 30: criteria.v1.ServerService.ListAgents:output_type -> criteria.v1.ListAgentsResponse
	1,  // 31: criteria.v1.ServerService.GetAgent:output_type -> criteria.v1.Agent
	6,  // 32: criteria.v1.ServerService.ListRuns:output_type -> criteria.v1.ListRunsResponse
	28, // 33: criteria.v1.ServerService.GetRun:output_type -> criteria.v1.Run
	9,  // 34: criteria.v1.ServerService.ListRunEvents:output_type -> criteria.v1.ListRunEventsResponse
	29, // 35: criteria.v1.ServerService.WatchRun:output_type -> criteria.v1.Envelope
	12, // 36: criteria.v1.ServerService.StopRun:output_type -> criteria.v1.StopRunResponse
	14, // 37: criteria.v1.ServerService.PauseRun:output_type -> criteria.v1.PauseRunResponse
	16, // 38: criteria.v1.ServerService.ResumeRun:output_type -> criteria.v1.ResumeRunResponse
	18, // 39: criteria.v1.ServerService.InspectRun:output_type -> criteria.v1.InspectRunResponse
	22, // 40: criteria.v1.ServerService.SubmitWorkflowAssignment:output_type -> criteria.v1.SubmitWorkflowAssignmentResponse
	24, // 41: criteria.v1.ServerService.GetAssignmentDisposition:output_type -> criteria.v1.GetAssignmentDispositionResponse
	20, // 42: criteria.v1.ServerService.SendPrompt:output_type -> criteria.v1.SendPromptResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_criteria_v1_server_proto_init() }
func file_criteria_v1_server_proto_init() {
	if File_criteria_v1_server_proto != nil {
		return
	}
	file_criteria_v1_events_proto_init()
	file_criteria_v1_criteria_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v1_server_proto_rawDesc), len(file_criteria_v1_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v1_server_proto_goTypes,
		DependencyIndexes: file_criteria_v1_server_proto_depIdxs,
		EnumInfos:         file_criteria_v1_server_proto_enumTypes,
		MessageInfos:      file_criteria_v1_server_proto_msgTypes,
	}.Build()
	File_criteria_v1_server_proto = out.File
	file_criteria_v1_server_proto_goTypes = nil
	file_criteria_v1_server_proto_depIdxs = nil
}
