apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: criteria-jobs

resources:
  - manager/namespace.yaml
  - crd/bases/criteria.brokenbots.dev_criteriaruns.yaml
  - rbac/role.yaml
  - manager/deployment.yaml
